apiVersion: v1
kind: Service
metadata:
  name: usuariocn10Version2
spec:
  selector:
    app: usuariocn10Version2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
