apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata: 
  generateName: list-directory-
spec: 
  taskRef: 
    name: list-directory
  podTemplate: 
    securityContext: 
      fsGroup: 65532
  workspaces: 
    - name: output
      persistentVolumeClaim: 
        claimName: workspace
