apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  namespace: diploe2-vgfc
  annotations:
    tekton.dev/docker-0: https://gcr.io # Described below
type: kubernetes.io/basic-auth
stringData:
  username: vianeyflores
  password: dmlhbmV5ZmxvcmVzOkVsZWN0cm9ob3VzZTFf
