apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-role
  namespace: diploe2-vgfc
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
